CREATE DATABASE `rrs_db`;
drop database `rrs_db`;
drop table `USERS`;
drop table `COMMUNITIES`;
drop table `COMMUNITY_ATTACHMENTS`;
drop table `COMMUNITY_COMMENTS`;

USE `rrs_db`;

CREATE TABLE `USERS` (
	`ID` bigint unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '유저ID 기본키',
	`USER_NAME` VARCHAR(50) NOT NULL COMMENT '유저 이름',
	`USER_ID` VARCHAR(50) UNIQUE NOT NULL COMMENT '유저 로그인 아이디(중복안됨)',
	`USER_PASSWORD` VARCHAR(50) NOT NULL COMMENT '유저 로그인 비밀번호',
	`USER_NICK_NAME` VARCHAR(50) UNIQUE NOT NULL COMMENT '유저 닉네임(중복안됨)',
	`USER_PHONE` CHAR(11) UNIQUE NOT NULL COMMENT '휴대폰 번호(중복안됨)',
	`USER_ADDRESS` VARCHAR(255) NOT NULL COMMENT '주소',
	`USER_ADDRESS_DETAIL` VARCHAR(255) NOT NULL COMMENT '주소 상세',
	`USER_EMAIL` VARCHAR(255) UNIQUE NOT NULL COMMENT '유저 이메일 (중복안됨)',
	`USER_PROFILE_IMAGE_URL` VARCHAR(255) COMMENT '프로필 사진 주소',
	`USER_IS_DELETED` CHAR(1) DEFAULT 1 NOT NULL COMMENT '삭제여부 O: 삭제, 1: 사용',
	`USER_CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간'
);

CREATE TABLE `COMMUNITIES` (
	`COMMUNITY_ID` bigint unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티ID 기본키',
	`ID` bigint unsigned NOT NULL COMMENT '유저ID 기본키',
	`COMMUNITY_TITLE` VARCHAR(255) NOT NULL COMMENT '커뮤니티 제목',
	`COMMUNITY_LIKE_COUNT` int unsigned NOT NULL DEFAULT 0 COMMENT '좋아요 수',
	`COMMUNITY_CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
	`COMMUNITY_UPDATE_AT` DATETIME NULL COMMENT '수정 시간',
	`COMMUNITY_CONTENTS` TEXT NOT NULL COMMENT '내용',
	`COMMUNITY_THUMB_NAIL_IMG_URL` VARCHAR(255) NULL COMMENT '썸네일 이미지 URL',
	FOREIGN KEY (`ID`) REFERENCES `USERS` (`ID`)
);

CREATE TABLE `COMMUNITY_ATTACHMENTS` (
	`COMMUNITY_ATTACHMENT_ID` bigint unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 첨부파일ID 기본키',
	`COMMUNITY_ID` bigint unsigned NOT NULL COMMENT '커뮤니티ID 기본키',
	`COMMUNITY_ATTACHMENT_IMAGE_URL` VARCHAR(255) NULL COMMENT '첨부 이미지 URL',
	FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`COMMUNITY_ID`)
);

CREATE TABLE `COMMUNITY_COMMENTS` (
	`COMMUNITY_COMMENTS_ID` bigint unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 댓글ID 기본키',
	`COMMUNITY_ID` bigint unsigned NOT NULL COMMENT '커뮤니티ID 기본키',
	`ID` bigint unsigned NOT NULL COMMENT '유저ID 기본키',
	`COMMUNITY_COMMENTS_PARENT_REPLY` CHAR(1) NOT NULL COMMENT '원댓글 여부 0: 원댓글, 1: 대댓글',
	`COMMUNITY_COMMENTS_CONTENTS` VARCHAR(255) NOT NULL COMMENT '댓글 내용',
	FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`COMMUNITY_ID`),
	FOREIGN KEY (`ID`) REFERENCES `USERS` (`ID`)
);