CREATE DATABASE `rrs_db`;
DROP DATABASE IF EXISTS `rrs_db`;

USE `rrs_db`;

DROP TABLE IF EXISTS `TODOS`;
DROP TABLE IF EXISTS `COMMUNITY_COMMENTS`;
DROP TABLE IF EXISTS `COMMUNITY_ATTACHMENTS`;
DROP TABLE IF EXISTS `COMMUNITIES`;
DROP TABLE IF EXISTS `USERS`;

-- USERS 테이블 생성
CREATE TABLE `USERS` (
    `ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '유저ID 기본키',
    `USER_NAME` VARCHAR(50) NOT NULL COMMENT '유저 이름',
    `USER_ID` VARCHAR(50) UNIQUE NOT NULL COMMENT '유저 로그인 아이디(중복안됨)',
    `USER_PASSWORD` VARCHAR(255) NOT NULL COMMENT '유저 로그인 비밀번호',
    `USER_NICK_NAME` VARCHAR(50) UNIQUE NOT NULL COMMENT '유저 닉네임(중복안됨)',
    `USER_PHONE` CHAR(11) UNIQUE NOT NULL COMMENT '휴대폰 번호(중복안됨)',
    `USER_ADDRESS` VARCHAR(255) NOT NULL COMMENT '주소',
    `USER_ADDRESS_DETAIL` VARCHAR(255) NOT NULL COMMENT '주소 상세',
    `USER_EMAIL` VARCHAR(255) UNIQUE NOT NULL COMMENT '유저 이메일 (중복안됨)',
    `USER_PROFILE_IMAGE_URL` VARCHAR(255) COMMENT '프로필 사진 주소'
);

-- COMMUNITIES 테이블 생성
CREATE TABLE `COMMUNITIES` (
    `COMMUNITY_ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티ID 기본키',
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '유저ID 기본키',
    `COMMUNITY_TITLE` VARCHAR(255) NOT NULL COMMENT '커뮤니티 제목',
    `COMMUNITY_LIKE_COUNT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '좋아요 수',
    `COMMUNITY_CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `COMMUNITY_UPDATE_AT` DATETIME NULL COMMENT '수정 시간',
    `COMMUNITY_CONTENTS` TEXT NOT NULL COMMENT '내용',
    `COMMUNITY_THUMB_NAIL_IMG_URL` VARCHAR(255) NULL COMMENT '썸네일 이미지 URL',
    FOREIGN KEY (`ID`) REFERENCES `USERS` (`ID`)
);

-- COMMUNITY_ATTACHMENTS 테이블 생성
CREATE TABLE `COMMUNITY_ATTACHMENTS` (
    `COMMUNITY_ATTACHMENT_ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 첨부파일ID 기본키',
    `COMMUNITY_ID` BIGINT UNSIGNED NOT NULL COMMENT '커뮤니티ID 기본키',
    `COMMUNITY_ATTACHMENT_IMAGE_URL` VARCHAR(255) NULL COMMENT '첨부 이미지 URL',
    FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`COMMUNITY_ID`) ON DELETE CASCADE
);

-- COMMUNITY_COMMENTS 테이블 생성
CREATE TABLE `COMMUNITY_COMMENTS` (
    `COMMUNITY_COMMENTS_ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 댓글ID 기본키',
    `COMMUNITY_ID` BIGINT UNSIGNED NOT NULL COMMENT '커뮤니티ID 기본키',
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '유저ID 기본키',
    `PARENT_COMMENT_ID` BIGINT UNSIGNED NULL COMMENT '부모 댓글 ID (null이면 원댓글)',
    `COMMUNITY_COMMENTS_CONTENTS` VARCHAR(255) NOT NULL COMMENT '댓글 내용',
    FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`COMMUNITY_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PARENT_COMMENT_ID`) REFERENCES `COMMUNITY_COMMENTS` (`COMMUNITY_COMMENTS_ID`) ON DELETE CASCADE
);

-- TODOS 테이블 생성
CREATE TABLE `TODOS` (
    `TODO_ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '오늘할일ID 기본키',
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '유저ID 기본키',
    `TODO_PREPARATION_CONTENT` VARCHAR(255) NOT NULL COMMENT '작성 내용',
    `TODO_CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    FOREIGN KEY (`ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE
);
